name: Pull Request Build

on:
    workflow_dispatch:

jobs:
    ubuntu-build:
        name: Build on Ubuntu
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2

            -   name: Testing the Dashboard Generation
                uses: ballerina-platform/ballerina-action@2201.0.3
                with:
                    args:
                        test
                env:
                    WORKING_DIR: ./dashboard
                    BALLERINA_BOT_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
